modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/Mrbysco/FlowerPatch/issues"
license="MIT"

[[mods]]
modId="flowerpatch"
version="${file.jarVersion}"
displayName="Flower Patch"
displayURL="https://www.curseforge.com/minecraft/mc-mods/flower-patch"
authors="Mrbysco, ShyNieke"
description='''
Allows you to combine multiple of the same flower similar to how you can have multiple sea pickles and candles in a block space.
'''
[[dependencies.flowerpatch]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.flowerpatch]]
modId="forge"
mandatory=true
versionRange="[44.1.0,)"
ordering="NONE"
side="BOTH"