modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/FlowerPatch/issues"
license="MIT"

[[mods]]
modId="flowerpatch"
version="${file.jarVersion}"
displayName="Flower Patch"
displayURL="https://www.curseforge.com/minecraft/mc-mods/flower-patch"
authors="Mrbysco, ShyNieke"
description='''
Allows you to combine multiple of the same flower similar to how you can have multiple sea pickles and candles in a block space.
'''
[[dependencies.flowerpatch]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.flowerpatch]]
modId="neoforge"
mandatory=true
versionRange="[20.2.59-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "flowerpatch.mixins.json"