modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/FlowerPatch/issues"
license="MIT"

[[mods]]
modId="flowerpatch"
version="${file.jarVersion}"
displayName="Flower Patch"
displayURL="https://www.curseforge.com/minecraft/mc-mods/flower-patch"
authors="Mrbysco, ShyNieke"
description='''
Allows you to combine multiple of the same flower similar to how you can have multiple sea pickles and candles in a block space.
'''
[[dependencies.flowerpatch]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.7,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.flowerpatch]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.7.1-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "flowerpatch.mixins.json"