# Project
version=7.0.1
group=com.mrbysco.flowerpatch

# Common
minecraft_version=1.21.1

# NeoForge
neo_version=21.1.90
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.110.0+1.21.1
fabric_loader_version=0.16.9
cloth_config_version=15.0.140
mod_menu_version=11.0.3

# Optional deps


# Mod options
mod_name=FlowerPatch
mod_author=Mrbysco
mod_id=flowerpatch

#Publishing
curseforge_id=641038
modrinth_id=8hbo1O1M

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false